language: node_js
node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - npm set progress=false

install:
  - npm install

script:
  - npm run test
  - npm run build

branches:
  only:
    - master
